 

try:
 a = 1
except Exception as e:
    print(f'the error --> {e}')


print('return')